# Units:
# time [s], distance [m], speed [m/s], acceleration [m/s^2]

CARLA:
  DT: 0.1                                                       # Set to -1 for variable time-step (real-world simulation)
  LANE_WIDTH: 3.5
  MAX_S: 3000                                                   # [int] max frenet s value available in global route

GYM_ENV:
  FIXED_REPRESENTATION: True                                    # actors's states have fixed positions in the observation tensor
  TRACK_LENGTH: 500                        # [int] distance to travel on s axis before terminating the episode. Must be less than CARLA.MAX_S - 50
  TARGET_SPEED: 13.89                                           # Ego's target speed
  MAX_SPEED: 25
  MAX_ACC: 6.878                                                # equivalent to 24.7608 km/h.s for Tesla model 3
  LOOK_BACK: 30                                                 # [int] Steps to look back at last path for observation sequence vector
  LOOP_BREAK: 100                                                # [int] steps to break path following while loop  - must be greater than LOOK_BACK

BEHAVIOR_PLANNER:
  MOBIL:
    PT: 4.0                                                     # Future propagation time
  IDM: { 'a_max': 6.878, 'delta': 4, 'T': 1.6, 'd0': 1, 'b': 5 } # a_max: ego max speed | delta:Acceleration exponent | T:  Safe time headway
                                                                 # d0: minimum distance gap | b: Desired deceleration:

LOCAL_PLANNER:
  MIN_SPEED: 13.89 # 5.56                                       # Allowed min speed for ego vehicle; RL's -1 action maps to this value
  MAX_SPEED: 15.28                                              # Allowed max speed for ego vehicle; RL's 1 action maps to this value

TRAFFIC_MANAGER:
  N_SPAWN_CARS: 15                                              # number of cars spawned at each episode
  MIN_SPEED: 8.33                                               # Min speed for actors in random traffic
  MAX_SPEED: 11.11                                              # Max speed for actors in random traffic